### PR TITLE
added Git commands and removed old test files

### PR DESCRIPTION
**Pull request by jayvala47**

### CODE REVIEW

**Review by gauravf16 — APPROVED** [review]
OK

**Review by gauravf16 — COMMENTED** [review]
two files deleted from the repo.

**Comment by swapnilshinde5** [comment]
Ok from my side

**Comment by swapnilshinde5** [comment]
re-checked

**Review by swapnilshinde5 — COMMENTED** [review]
Ok

**Review by 2907-ashish — APPROVED** [review]

**Review by swapnilshinde5 — APPROVED** [review]
Ok

**Pull request merged**
